version: 30.0.4
app_version: 3.8.0
listeners:
  client:
    protocol: 'PLAINTEXT'
image:
  repository: "bitnami/kafka"
  tag: "3.8.0-debian-12-r3"

# Disable KRaft mode, use Zookeeper
kraft:
  enabled: false

# Traditional Zookeeper mode configuration
controller:
  replicaCount: 0

broker:
  replicaCount: 3

zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: false
  image:
    registry: docker.io
    repository: zookeeper
    tag: "3.9.2"