apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-console-config
  namespace: bd-bd-gr-08
data:
  console.yaml: |
    kafka:
      brokers:
        - kafka-bootstrap.bd-bd-gr-08.svc.cluster.local:9092
    connect:
      enabled: true
      clusters:
        - name: Connectors
          url: http://kafka-connect.bd-bd-gr-08.svc.cluster.local:8083
    schemaRegistry:
      enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: bd-bd-gr-08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: console
          image: redpandadata/console:v2.7.0
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_FILE
              value: /etc/console/console.yaml
          volumeMounts:
            - name: console-config
              mountPath: /etc/console
              readOnly: true
      volumes:
        - name: console-config
          configMap:
            name: redpanda-console-config
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: bd-bd-gr-08
spec:
  selector:
    app: redpanda
  ports:
    - name: web
      port: 8082
      targetPort: 8082
