version: '3.8'

services:
  backend:
    image: dummystad/bigdata:backend-latest
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    image: dummystad/bigdata:frontend-latest
    build:
      context: ./frontend
      dockerfile: Dockerfile

  fetcher:
    image: dummystad/bigdata:fetcher-latest
    build:
      context: .
      dockerfile: Dockerfile.fetcher

  kafka-connect:
    image: dummystad/bigdata:kafka-connect-latest
    build:
      context: ./Docker/kafka-connect
      dockerfile: Dockerfile

  prediction-service:
    image: dummystad/bigdata:prediction-service-latest
    build:
      context: ./Docker/prediction-service
      dockerfile: Dockerfile

  database-writer:
    image: dummystad/bigdata:database-writer-latest
    build:
      context: ./Docker/database-writer
      dockerfile: Dockerfile
