apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregate-and-predict-service
  namespace: bd-bd-gr-08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregate-and-predict
  template:
    metadata:
      labels:
        app: aggregate-and-predict
    spec:
      containers:
      - name: service
        image: eclipse-temurin:17-jre
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            apt-get update -qq && apt-get install -y -qq python3 python3-pip > /dev/null 2>&1
            pip3 install -q --no-cache-dir --break-system-packages pyspark==4.1.0 kafka-python pandas numpy
            cd /app/SparkML
            python3 -u aggregate_and_predict_service.py
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-bootstrap:9092"
        - name: OUTPUT_TOPIC
          value: "energy_predictions"
        - name: CONSUMPTION_MODEL_PATH
          value: "/app/SparkML/models/energy_consumption_model_20251229_173121"
        - name: CHECK_INTERVAL
          value: "600"  # 10 minutes
        - name: JAVA_HOME
          value: "/opt/java/openjdk"
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: weather-data-pvc
      restartPolicy: Always
