apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
  namespace: bd-bd-gr-08
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://namenode-0.namenode.bd-bd-gr-08.svc.cluster.local:9000</value>
      </property>
      <property>
        <name>dfs.client.use.datanode.hostname</name>
        <value>true</value>
      </property>
    </configuration>
