apiVersion: v1
kind: ConfigMap
metadata:
  name: dmi-api-config
data:
  API_KEY: "b5800a05-4f0f-4584-b130-6129213728c0"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-historical-weather
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: data-fetch
        type: weather
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-namenode
          image: busybox:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "Waiting for NameNode..."
              until nc -z -v -w30 namenode 9000; do
                echo "Waiting for NameNode (namenode:9000)..."
                sleep 5
              done
              echo "NameNode is ready!"
      containers:
        - name: fetcher
          image: dummystad/bigdata:fetcher-latest
          imagePullPolicy: Always
          command: ["python", "/app/scripts/fetch_historical_weather.py"]
          args: ["--start-date", "2021-01-01", "--end-date", "2026-01-01"]
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          env:
            - name: DMI_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: dmi-api-config
                  key: API_KEY
      # No volume mount needed for data, as it uploads directly to HDFS
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-historical-energy
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: data-fetch
        type: energy
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-namenode
          image: busybox:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "Waiting for NameNode..."
              until nc -z -v -w30 namenode 9000; do
                echo "Waiting for NameNode (namenode:9000)..."
                sleep 5
              done
              echo "NameNode is ready!"
      containers:
        - name: fetcher
          image: dummystad/bigdata:fetcher-latest
          imagePullPolicy: Always
          command: ["python", "/app/scripts/fetch_historical_energy.py"]
          args: ["--start-date", "2021-01-01", "--end-date", "2026-01-01"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
