apiVersion: batch/v1
kind: Job
metadata:
  name: replay-history
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: replayer
          image: bigdata-fetcher:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "src/scripts/replay_to_kafka.py"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "energy-platform-energy-cluster:9092"
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: weather-data-pvc