apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service-hive
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction-service-hive
  template:
    metadata:
      labels:
        app: prediction-service-hive
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: predictor
        image: dummystad/bigdata:prediction-service-latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Release.Name }}-energy-cluster:9092"
        - name: OUTPUT_TOPIC
          value: "energy_predictions"
        # Updated to use generic model names (after renaming locally)
        - name: PRODUCTION_MODEL_PATH
          value: "/app/SparkML/models/production_model"
        - name: CONSUMPTION_MODEL_PATH
          value: "/app/SparkML/models/consumption_model"
        - name: CHECK_INTERVAL
          value: "300"
        - name: HADOOP_USER_NAME
          value: "root"
      restartPolicy: Always