apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.timescaledb.password | quote }}
  connection-string: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.timescaledb.user .Values.timescaledb.password .Values.timescaledb.host .Values.timescaledb.port .Values.timescaledb.database | quote }}
