apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-client-config
  namespace: {{ .Release.Namespace }}
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://namenode:9000</value>
      </property>
    </configuration>
