apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: weather-live-ingest
  labels:
    strimzi.io/cluster: energy-cluster
  namespace: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 Days
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: energy-predictions-output
  labels:
    strimzi.io/cluster: energy-cluster
  namespace: kafka
spec:
  partitions: 3
  replicas: 1